In [1]:
import pandas as pd
import numpy as np

In [2]:
nav = pd.read_csv("../data/raw/02_nav_history.csv")

In [3]:
nav.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [4]:
nav.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [5]:
nav.isnull(). sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [6]:
nav.duplicated(). sum()

np.int64(0)

In [7]:
nav.dtypes

amfi_code      int64
date             str
nav          float64
dtype: object

In [8]:
nav["date"] = pd.to_datetime(nav["date"])

In [9]:
nav.dtypes

amfi_code             int64
date         datetime64[us]
nav                 float64
dtype: object

In [10]:
nav = nav.sort_values(by=["amfi_code", "date"])

In [11]:
nav.head()

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639

In [12]:
nav["nav"] = nav["nav"].ffill()

In [13]:
nav = nav.drop_duplicates()

In [14]:
nav.duplicated().sum()

np.int64(0)

In [15]:
(nav["nav"] > 0).all()

np.True_

In [16]:
nav.to_csv("../data/processed/02_nav_history_cleaned.csv", index=False)

In [17]:
transactions = pd.read_csv("../data/raw/08_investor_transactions.csv")

In [18]:
transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [19]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [20]:
transactions.dtypes

investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

In [21]:
transactions["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [22]:
transactions["transaction_type"] = (
    transactions["transaction_type"]
    .str.strip()
)

transactions["transaction_type"] = transactions["transaction_type"].replace({
    "sip": "SIP",
    "Sip": "SIP",
    "SIP": "SIP",
    "lumpsum": "Lumpsum",
    "Lumpsum": "Lumpsum",
    "redemption": "Redemption",
    "Redemption": "Redemption"
})

In [23]:
(transactions["amount_inr"] > 0).all()

np.True_

In [24]:
transactions["transaction_date"] = pd.to_datetime(transactions["transaction_date"])

In [25]:
transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [26]:
transactions["kyc_status"].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [27]:
transactions["kyc_status"] = (
    transactions["kyc_status"]
    .str.strip()
    .str.title()
)

In [28]:
transactions.to_csv(
    "../data/processed/08_investor_transactions_cleaned.csv",
    index=False
)

In [29]:
performance = pd.read_csv("../data/raw/07_scheme_performance.csv")

In [30]:
performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [31]:
performance.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [32]:
performance.dtypes

amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

In [33]:
performance[
    ["return_1yr_pct",
     "return_3yr_pct",
     "return_5yr_pct"]
].describe()

       return_1yr_pct  return_3yr_pct  return_5yr_pct
count       40.000000       40.000000       40.000000
mean        14.376000       14.089000       14.516750
std          4.883023        4.617253        4.454021
min          4.260000        5.140000        5.430000
25%         11.735000       12.035000       12.340000
50%         14.620000       14.205000       14.185000
75%         16.392500       15.882500       17.585000
max         24.930000       23.390000       23.800000

In [34]:
(
    performance["expense_ratio_pct"]
    .between(0.1, 2.5)
).all()

np.True_

In [35]:
performance.to_csv(
    "../data/processed/07_scheme_performance_cleaned.csv",
    index=False
)

## SQLite Database Creation

In [36]:
from sqlalchemy import create_engine

In [37]:
engine = create_engine(
    "sqlite:///../data/db/bluestock_mf.db"
)

print("Database connection created!")

Database connection created!

In [38]:
import os

os.listdir("../data/processed")

['01_fund_master_cleaned.csv',
 '02_nav_history_cleaned.csv',
 '03_aum_by_fund_house_cleaned.csv',
 '04_monthly_sip_inflows_cleaned.csv',
 '05_category_inflows_cleaned.csv',
 '06_industry_folio_count_cleaned.csv',
 '07_scheme_performance_cleaned.csv',
 '08_investor_transactions_cleaned.csv',
 '09_portfolio_holdings_cleaned.csv',
 '10_benchmark_indices_cleaned.csv']

In [39]:
import pandas as pd

nav = pd.read_csv(
    "../data/processed/02_nav_history_cleaned.csv"
)

nav.to_sql(
    "fact_nav",
    engine,
    if_exists="replace",
    index=False
)

print("fact_nav table created!")

fact_nav table created!

In [40]:
pd.read_sql(
    "SELECT * FROM fact_nav LIMIT 5",
    engine
)

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

In [41]:
transactions = pd.read_csv(
    "../data/processed/08_investor_transactions_cleaned.csv"
)

transactions.to_sql(
    "fact_transactions",
    engine,
    if_exists="replace",
    index=False
)

print("fact_transactions created!")

fact_transactions created!

In [42]:
performance = pd.read_csv(
    "../data/processed/07_scheme_performance_cleaned.csv"
)

performance.to_sql(
    "fact_performance",
    engine,
    if_exists="replace",
    index=False
)

print("fact_performance created!")

fact_performance created!

In [43]:
pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table'",
    engine
)

                name
0           fact_aum
1           fact_nav
2  fact_transactions
3   fact_performance

In [44]:
print("NAV rows:", len(nav))
print("Transactions rows:", len(transactions))
print("Performance rows:", len(performance))

NAV rows: 46000
Transactions rows: 32778
Performance rows: 40

In [45]:
print(pd.read_sql("SELECT COUNT(*) FROM fact_nav", engine))
print(pd.read_sql("SELECT COUNT(*) FROM fact_transactions", engine))
print(pd.read_sql("SELECT COUNT(*) FROM fact_performance", engine))

   COUNT(*)
0     46000
   COUNT(*)
0     32778
   COUNT(*)
0        40

In [46]:
fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

fund_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

Cleaning AUM data

In [47]:
aum = pd.read_csv("../data/raw/03_aum_by_fund_house.csv")

In [48]:
aum.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     str
 1   fund_house      90 non-null     str
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.6 KB

In [49]:
aum['date'] = pd.to_datetime(aum['date'])

In [50]:
aum.duplicated().sum()

np.int64(0)

In [51]:
aum.isnull(). sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [52]:
(aum['aum_lakh_crore'] < 0). sum()

np.int64(0)

In [53]:
(aum['aum_crore']< 0). sum()

np.int64(0)

In [54]:
(aum["num_schemes"] < 0).sum()

np.int64(0)

In [55]:
aum.to_csv(
    "../data/processed/03_aum_by_fund_house_cleaned.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [56]:
aum.to_sql(
    "fact_aum",
    engine,
    if_exists="replace",
    index=False
)

print("fact_aum table created!")

fact_aum table created!

In [57]:
pd.read_sql(
    "SELECT COUNT(*) FROM fact_aum",
    engine
)

   COUNT(*)
0        90

In [58]:
fund = pd.read_csv('../data/raw/01_fund_master.csv')

In [59]:
fund.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [60]:
fund.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

In [61]:
fund['launch_date'] = pd.to_datetime(fund['launch_date'])

In [62]:
fund.duplicated(). sum()

np.int64(0)

In [63]:
fund.to_csv(
    "../data/processed/01_fund_master_cleaned.csv",
    index = False
)

In [64]:
sip = pd.read_csv("../data/raw/04_monthly_sip_inflows.csv")

In [65]:
sip.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [66]:
sip.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     str
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), str(1)
memory usage: 2.4 KB

In [67]:
sip["month"] = pd.to_datetime(sip["month"])

In [68]:
sip.duplicated(). sum()

np.int64(0)

In [69]:
sip.to_csv(
    "../data/processed/04_monthly_sip_inflows_cleaned.csv",
    index = False
)

In [70]:
category = pd.read_csv("../data/raw/05_category_inflows.csv")

In [71]:
category.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [72]:
category.info()

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    str
 1   category          144 non-null    str
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), str(2)
memory usage: 3.5 KB

In [73]:
category["month"] = pd.to_datetime(category["month"])

In [74]:
category.duplicated(). sum()

np.int64(0)

In [75]:
category.to_csv(
    "../data/processed/05_category_inflows_cleaned.csv",
    index = False
)

In [76]:
folio_count = pd.read_csv("../data/raw/06_industry_folio_count.csv")

In [77]:
folio_count.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [78]:
folio_count.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     str
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), str(1)
memory usage: 1.1 KB

In [79]:
folio_count["month"] = pd.to_datetime(folio_count["month"])

In [80]:
folio_count.duplicated(). sum()

np.int64(0)

In [81]:
folio_count.to_csv(
    "../data/processed/06_industry_folio_count_cleaned.csv",
    index = False
)

In [82]:
portfolio_holdings = pd.read_csv("../data/raw/09_portfolio_holdings.csv")

In [83]:
portfolio_holdings.info()

<class 'pandas.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    str
 2   stock_name         322 non-null    str
 3   sector             322 non-null    str
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    str
dtypes: float64(3), int64(1), str(4)
memory usage: 20.3 KB

In [84]:
portfolio_holdings.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [85]:
portfolio_holdings["portfolio_date0"] = pd.to_datetime(portfolio_holdings["portfolio_date"])

In [86]:
portfolio_holdings.duplicated(). sum()

np.int64(0)

In [87]:
portfolio_holdings.to_csv(
    "../data/processed/09_portfolio_holdings_cleaned.csv",
    index = False
)

In [88]:
benchmark = pd.read_csv("../data/raw/10_benchmark_indices.csv")

In [89]:
benchmark.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [90]:
benchmark.info()

<class 'pandas.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   str
 1   index_name   8050 non-null   str
 2   close_value  8050 non-null   float64
dtypes: float64(1), str(2)
memory usage: 188.8 KB

In [91]:
benchmark["date"] = pd.to_datetime(benchmark["date"])

In [92]:
benchmark.duplicated(). sum()

np.int64(0)

In [93]:
benchmark.to_csv(
    "../data/processed/10_benchmark_indices_cleaned.csv",
    index = False
)

In [94]:
aum["date"].unique()

<DatetimeArray>
['2022-03-31 00:00:00', '2022-09-30 00:00:00', '2023-03-31 00:00:00',
 '2023-09-30 00:00:00', '2024-03-31 00:00:00', '2024-09-30 00:00:00',
 '2024-12-31 00:00:00', '2025-03-31 00:00:00', '2025-12-31 00:00:00']
Length: 9, dtype: datetime64[us]