In [2]:
import pandas as pd
import numpy as np

In [3]:
nav = pd.read_csv("../data/raw/02_nav_history.csv")

In [4]:
nav.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [5]:
nav.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [6]:
nav.isnull(). sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [7]:
nav.duplicated(). sum()

np.int64(0)

In [8]:
nav.dtypes

amfi_code      int64
date             str
nav          float64
dtype: object

In [9]:
nav["date"] = pd.to_datetime(nav["date"])

In [10]:
nav.dtypes

amfi_code             int64
date         datetime64[us]
nav                 float64
dtype: object

In [11]:
nav = nav.sort_values(by=["amfi_code", "date"])

In [12]:
nav.head()

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639

In [13]:
nav["nav"] = nav["nav"].ffill()

In [14]:
nav = nav.drop_duplicates()

In [15]:
nav.duplicated().sum()

np.int64(0)

In [16]:
(nav["nav"] > 0).all()

np.True_

In [17]:
nav.to_csv("../data/processed/02_nav_history_cleaned.csv", index=False)

In [18]:
transactions = pd.read_csv("../data/raw/08_investor_transactions.csv")

In [19]:
transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [20]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [21]:
transactions.dtypes

investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

In [22]:
transactions["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [23]:
transactions["transaction_type"] = (
    transactions["transaction_type"]
    .str.strip()
)

transactions["transaction_type"] = transactions["transaction_type"].replace({
    "sip": "SIP",
    "Sip": "SIP",
    "SIP": "SIP",
    "lumpsum": "Lumpsum",
    "Lumpsum": "Lumpsum",
    "redemption": "Redemption",
    "Redemption": "Redemption"
})

In [24]:
(transactions["amount_inr"] > 0).all()

np.True_

In [25]:
transactions["transaction_date"] = pd.to_datetime(transactions["transaction_date"])

In [26]:
transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [27]:
transactions["kyc_status"].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [28]:
transactions["kyc_status"] = (
    transactions["kyc_status"]
    .str.strip()
    .str.title()
)

In [29]:
transactions.to_csv(
    "../data/processed/08_investor_transactions_cleaned.csv",
    index=False
)

In [30]:
performance = pd.read_csv("../data/raw/07_scheme_performance.csv")

In [31]:
performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [32]:
performance.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [33]:
performance.dtypes

amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

In [34]:
performance[
    ["return_1yr_pct",
     "return_3yr_pct",
     "return_5yr_pct"]
].describe()

       return_1yr_pct  return_3yr_pct  return_5yr_pct
count       40.000000       40.000000       40.000000
mean        14.376000       14.089000       14.516750
std          4.883023        4.617253        4.454021
min          4.260000        5.140000        5.430000
25%         11.735000       12.035000       12.340000
50%         14.620000       14.205000       14.185000
75%         16.392500       15.882500       17.585000
max         24.930000       23.390000       23.800000

In [35]:
(
    performance["expense_ratio_pct"]
    .between(0.1, 2.5)
).all()

np.True_

In [36]:
performance.to_csv(
    "../data/processed/07_scheme_performance_cleaned.csv",
    index=False
)

## SQLite Database Creation

In [37]:
from sqlalchemy import create_engine

In [38]:
engine = create_engine(
    "sqlite:///../data/db/bluestock_mf.db"
)

print("Database connection created!")

Database connection created!

In [39]:
import os

os.listdir("../data/processed")

['02_nav_history_cleaned.csv',
 '07_scheme_performance_cleaned.csv',
 '08_investor_transactions_cleaned.csv']

In [40]:
import pandas as pd

nav = pd.read_csv(
    "../data/processed/02_nav_history_cleaned.csv"
)

nav.to_sql(
    "fact_nav",
    engine,
    if_exists="replace",
    index=False
)

print("fact_nav table created!")

fact_nav table created!

In [41]:
pd.read_sql(
    "SELECT * FROM fact_nav LIMIT 5",
    engine
)

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

In [42]:
transactions = pd.read_csv(
    "../data/processed/08_investor_transactions_cleaned.csv"
)

transactions.to_sql(
    "fact_transactions",
    engine,
    if_exists="replace",
    index=False
)

print("fact_transactions created!")

fact_transactions created!

In [43]:
performance = pd.read_csv(
    "../data/processed/07_scheme_performance_cleaned.csv"
)

performance.to_sql(
    "fact_performance",
    engine,
    if_exists="replace",
    index=False
)

print("fact_performance created!")

fact_performance created!

In [44]:
pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table'",
    engine
)

                name
0           fact_nav
1  fact_transactions
2   fact_performance

In [45]:
print("NAV rows:", len(nav))
print("Transactions rows:", len(transactions))
print("Performance rows:", len(performance))

NAV rows: 46000
Transactions rows: 32778
Performance rows: 40

In [46]:
print(pd.read_sql("SELECT COUNT(*) FROM fact_nav", engine))
print(pd.read_sql("SELECT COUNT(*) FROM fact_transactions", engine))
print(pd.read_sql("SELECT COUNT(*) FROM fact_performance", engine))

   COUNT(*)
0     46000
   COUNT(*)
0     32778
   COUNT(*)
0        40

In [47]:
fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

fund_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

Cleaning AUM data

In [48]:
aum = pd.read_csv("../data/raw/03_aum_by_fund_house.csv")

In [49]:
aum.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     str
 1   fund_house      90 non-null     str
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.6 KB

In [52]:
aum['date'] = pd.to_datetime(aum['date'])

In [51]:
aum.duplicated().sum()

np.int64(0)

In [53]:
aum.isnull(). sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [60]:
(aum['aum_lakh_crore'] < 0). sum()

np.int64(0)

In [61]:
(aum['aum_crore']< 0). sum()

np.int64(0)

In [62]:
(aum["num_schemes"] < 0).sum()

np.int64(0)

In [63]:
aum.to_csv(
    "../data/processed/03_aum_by_fund_house_cleaned.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [64]:
aum.to_sql(
    "fact_aum",
    engine,
    if_exists="replace",
    index=False
)

print("fact_aum table created!")

fact_aum table created!

In [65]:
pd.read_sql(
    "SELECT COUNT(*) FROM fact_aum",
    engine
)

   COUNT(*)
0        90

In [66]:
nav.head()

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639